image: docker:latest

service:
- docker:dind

before_script:
- docker info

build:
  script:
    - ls
    - docker run fpco/stack-build pwd
    - docker run -v `pwd`:/workspace fpco/stack-build stack install

